using Demif.Application.Abstractions.Persistence;
using Demif.Application.Abstractions.Repositories;
using Demif.Application.Abstractions.Services;
using Demif.Application.Common.Models;
using Demif.Domain.Entities;
using Microsoft.Extensions.Logging;

namespace Demif.Application.Features.Lessons.Admin;

/// <summary>
/// Service tạo lesson từ YouTube URL.
/// 
/// Flow:
/// 1. Admin paste YouTube URL
/// 2. Fetch video metadata (title, thumbnail, duration) 
/// 3. Fetch captions → FullTranscript + TimedTranscript
/// 4. Auto-generate DictationTemplates cho 4 levels (Beginner → Expert)
/// 5. Tạo Lesson entity với đầy đủ data
/// 
/// User experience:
/// - Video embed trong app (iframe YouTube player)
/// - Player sync với TimedTranscript segments
/// - User nghe đoạn → điền từ bị ẩn → submit chấm điểm
/// </summary>
public class YouTubeLessonService
{
    private readonly IYouTubeService _youTubeService;
    private readonly ILessonRepository _lessonRepository;
    private readonly IApplicationDbContext _dbContext;
    private readonly ILogger<YouTubeLessonService> _logger;

    public YouTubeLessonService(
        IYouTubeService youTubeService,
        ILessonRepository lessonRepository,
        IApplicationDbContext dbContext,
        ILogger<YouTubeLessonService> logger)
    {
        _youTubeService = youTubeService;
        _lessonRepository = lessonRepository;
        _dbContext = dbContext;
        _logger = logger;
    }

    /// <summary>
    /// Preview YouTube video trước khi tạo lesson.
    /// Admin xem info → quyết định tạo hay không.
    /// </summary>
    public async Task<Result<YouTubePreviewResponse>> PreviewAsync(
        string youtubeUrl, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(youtubeUrl))
            return Result.Failure<YouTubePreviewResponse>(Error.Validation("YouTube URL không được để trống."));

        var videoInfo = await _youTubeService.GetVideoInfoAsync(youtubeUrl, cancellationToken);
        if (videoInfo is null)
            return Result.Failure<YouTubePreviewResponse>(
                Error.Validation("Không thể lấy thông tin video. Kiểm tra lại URL hoặc video có thể bị private/xóa."));

        return Result.Success(new YouTubePreviewResponse
        {
            VideoId = videoInfo.VideoId,
            Title = videoInfo.Title,
            Description = TruncateDescription(videoInfo.Description),
            ChannelTitle = videoInfo.ChannelTitle,
            DurationSeconds = videoInfo.DurationSeconds,
            ThumbnailUrl = videoInfo.ThumbnailUrl,
            EmbedUrl = videoInfo.EmbedUrl,
            HasCaptions = videoInfo.HasCaptions,
            AvailableCaptionLanguages = videoInfo.AvailableCaptionLanguages,
            SuggestedCategory = SuggestCategory(videoInfo)
        });
    }

    /// <summary>
    /// Lấy transcript theo nhiều ngôn ngữ từ YouTube.
    /// Không ghi DB, chỉ trả dữ liệu để admin/frontend preview.
    /// </summary>
    public async Task<Result<YouTubeTranscriptsResponse>> GetTranscriptsAsync(
        string youtubeUrl,
        string preferredLanguage = "en",
        bool includeText = true,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(youtubeUrl))
            return Result.Failure<YouTubeTranscriptsResponse>(
                Error.Validation("YouTube URL không được để trống."));

        var videoInfo = await _youTubeService.GetVideoInfoAsync(youtubeUrl, cancellationToken);
        if (videoInfo is null)
            return Result.Failure<YouTubeTranscriptsResponse>(
                Error.Validation("Không thể lấy thông tin video. Kiểm tra lại URL hoặc video bị private/xóa."));

        var candidateLanguages = BuildCandidateLanguages(preferredLanguage, videoInfo.AvailableCaptionLanguages);
        var tracks = new List<YouTubeTranscriptTrackResponse>();

        foreach (var lang in candidateLanguages)
        {
            var captions = await _youTubeService.GetCaptionsAsync(videoInfo.VideoId, lang, cancellationToken);
            if (captions is null || string.IsNullOrWhiteSpace(captions.FullTranscript))
                continue;

            if (tracks.Any(t => t.Language.Equals(captions.Language, StringComparison.OrdinalIgnoreCase)))
                continue;

            tracks.Add(new YouTubeTranscriptTrackResponse
            {
                Language = captions.Language,
                IsAutoGenerated = captions.IsAutoGenerated,
                SegmentCount = captions.Segments.Count,
                WordCount = captions.FullTranscript.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length,
                FullTranscript = includeText ? captions.FullTranscript : string.Empty,
                TimedTranscript = includeText ? captions.TimedTranscriptJson : string.Empty
            });
        }

        var bestLanguage = ResolveBestLanguage(preferredLanguage, tracks.Select(t => t.Language).ToList());

        return Result.Success(new YouTubeTranscriptsResponse
        {
            VideoId = videoInfo.VideoId,
            Title = videoInfo.Title,
            EmbedUrl = videoInfo.EmbedUrl,
            DurationSeconds = videoInfo.DurationSeconds,
            RequestedLanguages = candidateLanguages,
            AvailableCaptionLanguages = videoInfo.AvailableCaptionLanguages,
            Tracks = tracks,
            BestLanguage = bestLanguage,
            Message = tracks.Count == 0
                ? "Không lấy được transcript từ các ngôn ngữ đã thử."
                : $"Đã lấy {tracks.Count} transcript track(s)."
        });
    }

    /// <summary>
    /// Tạo lesson từ YouTube URL — full auto pipeline.
    /// </summary>
    public async Task<Result<CreateLessonFromYouTubeResponse>> CreateFromYouTubeAsync(
        CreateLessonFromYouTubeRequest request, CancellationToken cancellationToken = default)
    {
        // 1. Validate input
        if (string.IsNullOrWhiteSpace(request.YouTubeUrl))
            return Result.Failure<CreateLessonFromYouTubeResponse>(
                Error.Validation("YouTube URL không được để trống."));

        // 2. Fetch video metadata
        var videoInfo = await _youTubeService.GetVideoInfoAsync(request.YouTubeUrl, cancellationToken);
        if (videoInfo is null)
            return Result.Failure<CreateLessonFromYouTubeResponse>(
                Error.Validation("Không thể lấy thông tin video. Kiểm tra lại URL hoặc video bị private/xóa."));

        if (videoInfo.DurationSeconds <= 0)
            return Result.Failure<CreateLessonFromYouTubeResponse>(
                Error.Validation("Không xác định được thời lượng video."));

        // 3. Fetch captions với fallback nhiều ngôn ngữ
        var transcriptResult = await GetTranscriptsAsync(
            request.YouTubeUrl,
            request.CaptionLanguage,
            includeText: true,
            cancellationToken);

        var transcriptData = transcriptResult.IsSuccess ? transcriptResult.Value : null;
        var selectedTrack = SelectBestTrack(request.CaptionLanguage, transcriptData?.Tracks);
        var hasCaptions = selectedTrack != null && !string.IsNullOrWhiteSpace(selectedTrack.FullTranscript);

        // 4. Build Lesson entity
        var lesson = new Lesson
        {
            Title = request.TitleOverride ?? videoInfo.Title,
            Description = request.DescriptionOverride ?? TruncateDescription(videoInfo.Description),
            LessonType = request.LessonType,
            Level = request.Level,
            Category = request.Category,

            // YouTube embed URL cho player
            AudioUrl = videoInfo.EmbedUrl,
            MediaUrl = videoInfo.EmbedUrl,
            MediaType = "youtube",

            DurationSeconds = videoInfo.DurationSeconds,
            ThumbnailUrl = videoInfo.ThumbnailUrl,

            // Transcript từ captions
            FullTranscript = hasCaptions ? selectedTrack!.FullTranscript : string.Empty,
            TimedTranscript = hasCaptions ? selectedTrack!.TimedTranscript : null,

            IsPremiumOnly = request.IsPremiumOnly,
            DisplayOrder = request.DisplayOrder,
            Tags = request.Tags,
            Status = request.Status
        };

        // 5. Auto-generate DictationTemplates (nếu có captions)
        if (hasCaptions && !string.IsNullOrWhiteSpace(lesson.TimedTranscript))
        {
            try
            {
                lesson.DictationTemplates = DictationTemplateGenerator.GenerateAllTemplates(lesson.TimedTranscript);
                _logger.LogInformation(
                    "Generated DictationTemplates cho YouTube video '{VideoId}' ({Segments} segments)",
                    videoInfo.VideoId, selectedTrack!.SegmentCount);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex,
                    "Không thể generate DictationTemplates cho video {VideoId}", videoInfo.VideoId);
                // Không throw — lesson vẫn tạo được, admin có thể regenerate sau
            }
        }
        else
        {
            _logger.LogWarning(
                "Video '{VideoId}' không có captions (lang: {Lang}). Lesson sẽ không có Dictation exercise.",
                videoInfo.VideoId, request.CaptionLanguage);
        }

        // 6. Save
        await _lessonRepository.AddAsync(lesson, cancellationToken);
        await _dbContext.SaveChangesAsync(cancellationToken);

        _logger.LogInformation(
            "Created lesson '{Title}' from YouTube video {VideoId} (Id: {LessonId}, captions: {HasCaptions})",
            lesson.Title, videoInfo.VideoId, lesson.Id, hasCaptions);

        // 7. Build response
        var transcriptWords = hasCaptions
            ? selectedTrack!.WordCount
            : 0;

        var response = new CreateLessonFromYouTubeResponse
        {
            LessonId = lesson.Id,
            Title = lesson.Title,
            VideoId = videoInfo.VideoId,
            EmbedUrl = videoInfo.EmbedUrl,
            DurationSeconds = lesson.DurationSeconds,
            ThumbnailUrl = lesson.ThumbnailUrl,
            HasCaptions = hasCaptions,
            CaptionLanguage = hasCaptions ? selectedTrack!.Language : null,
            IsAutoGeneratedCaptions = hasCaptions && selectedTrack!.IsAutoGenerated,
            CaptionSegmentCount = hasCaptions ? selectedTrack!.SegmentCount : 0,
            TranscriptWordCount = transcriptWords,
            AvailableTranscriptLanguages = transcriptData?.Tracks.Select(t => t.Language).ToList() ?? new List<string>(),
            HasDictationTemplates = !string.IsNullOrWhiteSpace(lesson.DictationTemplates),
            Status = lesson.Status,
            Message = BuildResultMessage(hasCaptions, selectedTrack, lesson)
        };

        return Result.Success(response);
    }

    #region Helpers

    private static string BuildResultMessage(bool hasCaptions, YouTubeTranscriptTrackResponse? selectedTrack, Lesson lesson)
    {
        if (!hasCaptions)
            return "⚠️ Lesson đã tạo nhưng KHÔNG có captions. Bạn cần thêm transcript thủ công để sử dụng Dictation.";

        if (string.IsNullOrWhiteSpace(lesson.DictationTemplates))
            return "⚠️ Lesson đã tạo có captions nhưng không thể generate DictationTemplates. Thử regenerate sau.";

        var autoNote = selectedTrack!.IsAutoGenerated ? " (auto-generated, có thể có lỗi nhỏ)" : " (manual, chất lượng cao)";
        return $"✅ Lesson đã tạo thành công với Dictation templates cho 4 levels! Captions: {selectedTrack.Language}{autoNote}";
    }

    private static YouTubeTranscriptTrackResponse? SelectBestTrack(
        string preferredLanguage,
        List<YouTubeTranscriptTrackResponse>? tracks)
    {
        if (tracks == null || tracks.Count == 0)
            return null;

        var exact = tracks.FirstOrDefault(t =>
            t.Language.Equals(preferredLanguage, StringComparison.OrdinalIgnoreCase));
        if (exact is not null) return exact;

        var normalizedPreferred = NormalizeLanguage(preferredLanguage);
        var normalizedMatch = tracks.FirstOrDefault(t =>
            NormalizeLanguage(t.Language).Equals(normalizedPreferred, StringComparison.OrdinalIgnoreCase));
        if (normalizedMatch is not null) return normalizedMatch;

        var englishTrack = tracks.FirstOrDefault(t =>
            NormalizeLanguage(t.Language).Equals("en", StringComparison.OrdinalIgnoreCase));
        if (englishTrack is not null) return englishTrack;

        return tracks[0];
    }

    private static List<string> BuildCandidateLanguages(string preferredLanguage, List<string> availableLanguages)
    {
        var candidates = new List<string>();

        if (!string.IsNullOrWhiteSpace(preferredLanguage))
            candidates.Add(preferredLanguage);

        var normalizedPreferred = NormalizeLanguage(preferredLanguage);
        if (!string.IsNullOrWhiteSpace(normalizedPreferred))
            candidates.Add(normalizedPreferred);

        candidates.Add("en");
        candidates.Add("en-US");

        candidates.AddRange(availableLanguages);

        return candidates
            .Where(l => !string.IsNullOrWhiteSpace(l))
            .Select(l => l.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string? ResolveBestLanguage(string preferredLanguage, List<string> availableTracks)
    {
        if (availableTracks.Count == 0)
            return null;

        var exact = availableTracks.FirstOrDefault(l =>
            l.Equals(preferredLanguage, StringComparison.OrdinalIgnoreCase));
        if (exact is not null) return exact;

        var normalizedPreferred = NormalizeLanguage(preferredLanguage);
        var normalized = availableTracks.FirstOrDefault(l =>
            NormalizeLanguage(l).Equals(normalizedPreferred, StringComparison.OrdinalIgnoreCase));
        if (normalized is not null) return normalized;

        var english = availableTracks.FirstOrDefault(l =>
            NormalizeLanguage(l).Equals("en", StringComparison.OrdinalIgnoreCase));
        if (english is not null) return english;

        return availableTracks[0];
    }

    private static string NormalizeLanguage(string? language)
    {
        if (string.IsNullOrWhiteSpace(language)) return string.Empty;
        var normalized = language.Trim();
        var dashIndex = normalized.IndexOf('-');
        if (dashIndex > 0)
            normalized = normalized[..dashIndex];
        return normalized;
    }

    private static string? TruncateDescription(string? description)
    {
        if (string.IsNullOrWhiteSpace(description)) return null;
        return description.Length > 500 ? description[..500] + "..." : description;
    }

    /// <summary>
    /// Đoán category từ video info (heuristic đơn giản)
    /// </summary>
    private static string? SuggestCategory(YouTubeVideoInfo info)
    {
        var text = $"{info.Title} {info.Description} {info.ChannelTitle}".ToLowerInvariant();

        if (text.Contains("ted") || text.Contains("lecture") || text.Contains("academic"))
            return "academic";
        if (text.Contains("business") || text.Contains("entrepreneur") || text.Contains("startup"))
            return "business";
        if (text.Contains("travel") || text.Contains("tourism") || text.Contains("trip"))
            return "travel";
        if (text.Contains("news") || text.Contains("bbc") || text.Contains("cnn"))
            return "news";
        if (text.Contains("ielts") || text.Contains("toefl") || text.Contains("toeic"))
            return "exam";
        if (text.Contains("movie") || text.Contains("film") || text.Contains("trailer"))
            return "entertainment";

        return "conversation";
    }

    #endregion
}
