using Demif.Domain.Enums;

namespace Demif.Application.Features.Lessons.Admin;

/// <summary>
/// Request tạo lesson từ YouTube URL.
/// Admin chỉ cần paste link → backend auto-fetch tất cả metadata + captions.
/// </summary>
public class CreateLessonFromYouTubeRequest
{
    /// <summary>
    /// YouTube URL hoặc Video ID.
    /// Hỗ trợ: watch?v=, youtu.be/, embed/, hoặc ID trực tiếp.
    /// </summary>
    public string YouTubeUrl { get; set; } = string.Empty;

    /// <summary>
    /// Ngôn ngữ captions muốn lấy (mặc định "en").
    /// </summary>
    public string CaptionLanguage { get; set; } = "en";

    /// <summary>
    /// Loại bài học
    /// </summary>
    public LessonType LessonType { get; set; } = LessonType.Dictation;

    /// <summary>
    /// Cấp độ mặc định (ảnh hưởng hiển thị, không ảnh hưởng DictationTemplates — templates sinh cho TẤT CẢ levels)
    /// </summary>
    public Level Level { get; set; } = Level.Beginner;

    /// <summary>
    /// Danh mục: conversation, business, travel, academic, news, entertainment
    /// </summary>
    public string? Category { get; set; }

    /// <summary>
    /// Chỉ Premium mới xem được
    /// </summary>
    public bool IsPremiumOnly { get; set; }

    /// <summary>
    /// Thứ tự hiển thị
    /// </summary>
    public int DisplayOrder { get; set; }

    /// <summary>
    /// Tags JSON array: ["business", "daily", "travel"]
    /// </summary>
    public string? Tags { get; set; }

    /// <summary>
    /// Trạng thái: draft, published, archived. Mặc định "draft" để admin review trước khi publish.
    /// </summary>
    public string Status { get; set; } = "draft";

    /// <summary>
    /// Override title (nếu null thì dùng title từ YouTube)
    /// </summary>
    public string? TitleOverride { get; set; }

    /// <summary>
    /// Override description (nếu null thì dùng description từ YouTube)
    /// </summary>
    public string? DescriptionOverride { get; set; }
}

/// <summary>
/// Response sau khi tạo lesson từ YouTube
/// </summary>
public class CreateLessonFromYouTubeResponse
{
    public Guid LessonId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string VideoId { get; set; } = string.Empty;
    public string EmbedUrl { get; set; } = string.Empty;
    public int DurationSeconds { get; set; }
    public string? ThumbnailUrl { get; set; }
    public bool HasCaptions { get; set; }
    public string? CaptionLanguage { get; set; }
    public bool IsAutoGeneratedCaptions { get; set; }
    public int CaptionSegmentCount { get; set; }
    public int TranscriptWordCount { get; set; }
    public bool HasDictationTemplates { get; set; }
    public string Status { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
}

/// <summary>
/// Response khi preview YouTube video trước khi tạo lesson
/// </summary>
public class YouTubePreviewResponse
{
    public string VideoId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? ChannelTitle { get; set; }
    public int DurationSeconds { get; set; }
    public string? ThumbnailUrl { get; set; }
    public string EmbedUrl { get; set; } = string.Empty;
    public bool HasCaptions { get; set; }
    public List<string> AvailableCaptionLanguages { get; set; } = new();
    public string? SuggestedCategory { get; set; }
}
