namespace Demif.Application.Abstractions.Services;

/// <summary>
/// Interface cho YouTube Data API v3 — fetch video metadata + captions
/// </summary>
public interface IYouTubeService
{
    /// <summary>
    /// Lấy metadata video: title, description, duration, thumbnail, channel
    /// </summary>
    Task<YouTubeVideoInfo?> GetVideoInfoAsync(string videoIdOrUrl, CancellationToken cancellationToken = default);

    /// <summary>
    /// Lấy captions (phụ đề) gồm timed segments.
    /// Ưu tiên: manual captions → auto-generated captions.
    /// Trả về null nếu video không có captions.
    /// </summary>
    Task<YouTubeCaptionResult?> GetCaptionsAsync(string videoId, string language = "en", CancellationToken cancellationToken = default);
}

/// <summary>
/// Metadata video YouTube
/// </summary>
public class YouTubeVideoInfo
{
    public string VideoId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? ChannelTitle { get; set; }
    public int DurationSeconds { get; set; }
    public string? ThumbnailUrl { get; set; }
    public string EmbedUrl => $"https://www.youtube.com/embed/{VideoId}";
    public string WatchUrl => $"https://www.youtube.com/watch?v={VideoId}";
    public bool HasCaptions { get; set; }
    public List<string> AvailableCaptionLanguages { get; set; } = new();
}

/// <summary>
/// Kết quả captions từ YouTube
/// </summary>
public class YouTubeCaptionResult
{
    public string VideoId { get; set; } = string.Empty;
    public string Language { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Full transcript (toàn bộ text nối lại)
    /// </summary>
    public string FullTranscript { get; set; } = string.Empty;

    /// <summary>
    /// Timed segments JSON: [{"startTime": 0.0, "endTime": 2.5, "text": "Hello"}]
    /// Map trực tiếp vào Lesson.TimedTranscript
    /// </summary>
    public string TimedTranscriptJson { get; set; } = string.Empty;

    /// <summary>
    /// Danh sách segments raw (trước khi serialize)
    /// </summary>
    public List<CaptionSegment> Segments { get; set; } = new();
}

public class CaptionSegment
{
    public double StartTime { get; set; }
    public double EndTime { get; set; }
    public string Text { get; set; } = string.Empty;
}
